services:
  - type: web
    name: lifebalance
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://osgefzwzzlkwxvrnojov.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: sb_publishable_awqUDnT_OvPfiHq8uk0hSw_2CsJsJWf
